services:
  db:
    image: postgres
    ports: 
      - 5432:5432
    volumes: 
      - ~/pgsql:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=corrigiaidb