FROM node:alpine

RUN npm install -g tsx
RUN mkdir -p /package
RUN mkdir -p /application
WORKDIR /application

ENV PORT 8080
ENV ADDRESS 0.0.0.0
EXPOSE 8080


ENV NODE_PATH /package/node_modules
COPY package.json /package/package.json
RUN npm install --prefix /package

COPY . /application
RUN npx prisma generate
