'use client'

import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import bg from '@/../public/images/bg.png'
import './globals.css'
import { createContext, useState } from 'react'
import { ThemeContext } from './context'

const poppins = Poppins({
  subsets: ['devanagari'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
})

const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const [theme, setTheme] = useState<'light' | 'dark'>('light')

  return (
    <ThemeContext.Provider
      value={{
        theme,
        setTheme,
      }}
    >
      <html
        lang="pt-BR"
        className="bg-[#FAFBFC] dark:bg-[#05071D] bg-bg bg-center bg-cover bg-no-repeat"
      >
        <body className={poppins.className}>{children}</body>
      </html>
    </ThemeContext.Provider>
  )
}
